version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: wallet_manager_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - wallet_manager_network

  app:
    image: wallet-manager
    container_name: wallet_manager_app
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - wallet_manager_network

networks:
  wallet_manager_network:
    driver: bridge
